### ISSUE TITLE
Combination of cacheflag with key doesn't break cache

### ISSUE THREAD

**Issue by TomDeSmet** [mmikkel/CacheFlag-Craft3#10]
My issue that brought me to using cacheflag:

I have a matrix block (a page content builder) where I cache every block's template by using the block UID. This allows the client to add multiple blocks of the same type with different content to a single page.

```
{% cache using key 'grid-component-' ~ self.uid %}
    block template content
{% endcache %}
```

However, when a block has a related entry field, upon making changes to that related entry, the cache doesn't know that when the related entry changed it should also break the cache of the template block. There's no template cache query that links the two.

In comes cacheflag: so I cache my blocks with a flag:

```
{% cacheflag flagged "c-strengths" %}
    block template content
{% endcache %}
```

Whenever an entry changes in the channel linked to ```c-strengths``` the blocks template cache gets erased. But, now the client can't add multiple versions of the same block type to the page as there is only a single cache per template.

But, fortunately cacheflag supports all the same properties as the normal cache, so I do this:

```
{% cacheflag flagged "c-strengths" using key 'grid-component-' ~ self.uid %}
    block template content
{% endcache %}
```

But (and here comes the new problem) now the cache is cleared whenever I update one of the related entries, **but if I make changes to the matrix block inside the entry itself, the entry page doesn't get updated anymore**!

So it seems either we use cache or cacheflag but not both... which is weird because I would swear I have used it like this in Craft 2 before.

**Comment by mmikkel** [comment]
> However, when a block has a related entry field, upon making changes to that related entry, the cache doesn't know that when the related entry changed it should also break the cache of the template block. There's no template cache query that links the two.

That sounds odd. You've omitted the "block template content" so I can't speak to why Craft doesn't save those related entry element queries as template cache criteria, but normally the `{% cache %}` tag would pick up on any element queries running inside, and break the cache automatically when need be.

> if I make changes to the matrix block inside the entry itself, the entry page doesn't get updated anymore!

Yeah, this is expected behaviour. A quick fix is to add the `c-strengths` flag to all sections using the page builder Matrix field, too (or add different flags to those sections, and use the pipe delimiter to tell CacheFlag to break the cache on multiple flags):

```twig
{% cacheflag flagged "c-strengths|news|frontpage" using key 'grid-component-' ~ self.uid %}
    ...
{% endcacheflag %}
```

**Comment by TomDeSmet** [comment]
Sorry, my mistake. There was a cache tag around the content grid in another template also.
So the default cache tag worked as it should. I didn't need cacheflag after all.
But, still a great plugin that saved a previous project of mine!

**Comment by mmikkel** [comment]
@TomDeSmet Great, thanks for the follow-up!
