### ISSUE TITLE
Migration error: Incorrect datetime value: '0000-00-00 00:00:00' for column 'dateCreated'

### ISSUE THREAD

**Issue by rungta** [mmikkel/CacheFlag-Craft3#12]
https://github.com/mmikkel/CacheFlag-Craft3/blob/5d941c8289694bca0a31ab6d6f801f69272e2e37/src/migrations/m200720_194731_add_missing_audit_columns.php#L31

This line is throwing an SQL exception with the error message:
> Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'dateCreated' at row 1
The SQL being executed was: ALTER TABLE `cacheflag_flags` ADD `dateCreated` datetime(0) NOT NULL

MySQL 5.7.17
Craft 3.4.30 -> 3.5.16
CacheFlag 1.0.4 -> 1.2.3

**Comment by mmikkel** [comment]
Thanks for reporting! This issue is resolved in [Cache Flag 1.2.4](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.2.4).

**Comment by strandofgenius** [comment]
@mmikkel I am running into this error when I run `php craft db/convert-charset` after upgrading from Craft 3 -> 4. I was already on version `1.4.1` when I did the upgrade.
