### ISSUE TITLE
Persistent event deprecation notice if the debug toolbar is enabled

### ISSUE THREAD

**Issue by rungta** [mmikkel/CacheFlag-Craft3#13]
https://github.com/mmikkel/CacheFlag-Craft3/blob/5d941c8289694bca0a31ab6d6f801f69272e2e37/src/services/CacheFlagService.php#L320-L327

Ran into a weird scenario:
- We have the [deprecator component throw exceptions in dev mode][1]
- I have the debug toolbar enabled in the control panel
- Anytime I save/edit any element in the control panel, an exception is thrown and the save fails

I `grep`'d the entire `vendor` folder and found no event handlers for any of the deprecated CacheFlag events and was stumped for a while. After debugging a little further I realised that the yii2-debug toolbar [registers a wildcard event handler `'*'`][2] which leads to `$this->hasEventHandlers(self::EVENT_BEFORE_DELETE_FLAGGED_CACHES)` returning `true`, which leads to this deprecated event being triggered on save …

I have been able to get around this for now by disabling the debug toolbar in the control panel, but that does not seem ideal.

[1]:https://twitter.com/nystudio107/status/1116727868581711874
[2]:https://github.com/yiisoft/yii2-debug/blob/3da86af0addb5d31e6f3372c46105900b7bd3734/src/panels/EventPanel.php#L38

**Comment by mmikkel** [comment]
Thanks for reporting! This issue is resolved in [Cache Flag 1.2.4](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.2.4).
