### ISSUE TITLE
Craft 4 - PHP Compile Error

### ISSUE THREAD

**Issue by rungta** [mmikkel/CacheFlag-Craft3#19]
Getting an error when trying to use the Yii debug toolbar in Craft 4

https://github.com/mmikkel/CacheFlag-Craft3/blob/3b17b1232c4b11e8edf35088ae06421339b870d9/src/controllers/CachesController.php#L20

```
yii\base\ErrorException: Type of mmikkel\cacheflag\controllers\CachesController::$allowAnonymous must be array|int|bool (as in class craft\web\Controller) in ../vendor/mmikkel/cache-flag/src/controllers/CachesController.php:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/663677/218266956-af074f29-fd67-4d6f-bd64-5f8734e92350.png">

**Comment by mmikkel** [comment]
Thanks for reporting that! Just released [Cache Flag 1.3.3](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.3.3) with a fix for this issue.
