### ISSUE TITLE
Issues Updating From Craft 2

### ISSUE THREAD

**Issue by benjaminkohl** [mmikkel/CacheFlag-Craft3#2]
We noticed the table names have changed for Craft 3 and there doesn't appear to be logic in the Install.php file for upgrading from Craft 2. This caused issues when we updated a site and enabled caching. We had to uninstall the plugin then install it again to get the new tables.

**Comment by mmikkel** [comment]
Hi @benjaminkohl – yeah, I haven't written an Install migration for Cache Flag. I'll try to find the time and will update this issue if/when I do. Pull requests are also very welcome, if you'd want to take a stab at it :)

**Comment by mmikkel** [comment]
Took me long enough, but I just added a Craft 2 migration to [Cache Flag 1.2.0](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.2.0). Unfortunately this version requires Craft 3.5.0-RC1 or later, but at least it's there for future Craft 2 upgrades :)
