### ISSUE TITLE
Possible to disable locally but not in production

### ISSUE THREAD

**Issue by CreateSean** [mmikkel/CacheFlag-Craft3#27]
Is it possible to disable cacheflag locally via a config file?

**Comment by mmikkel** [comment]
Just like the native `{% cache %}` tag, the `{% cacheflag %}` tag shouldn't cache anything if the [`enableTemplateCaching`](https://craftcms.com/docs/4.x/config/general.html#enabletemplatecaching) config setting is set to `false` for your local environment.

Additionally, again like the native `{% cache %}` tag you can conditionally disable specific `{% cacheflag %}` tags via the `unless` directive:

```twig
{% set env = getenv('CRAFT_ENVIRONMENT') %}

...
{% cacheflag flagged "foobar" unless env == 'dev' %}
...
{% endcacheflag %}
```

**Comment by CreateSean** [comment]
Thanks, I forgot about that config setting. All good now.
