### ISSUE TITLE
Unable to save more than one flag when running PHP 7.2

### ISSUE THREAD

**Issue by bernsno** [mmikkel/CacheFlag-Craft3#3]
We're experiencing an issue running Cache-Flag in PHP 7.2 which is related to a known issue in Yii: https://github.com/yiisoft/yii/issues/4167. 

We have one flag currently set in the CP. When we try to add additional flags beneath it we get the error `PHP 7.2: count(): Parameter must be an array or an object that implements Countable` and when the page is reloaded the new flag is gone. If we add a flag above the existing one we see the same error but when the page is reloaded the new flag remains.

We have not been able to replicate the issue in PHP 7.1 with the same data store (postgres). There are no errors appearing in the PHP or Web log for Craft.

![cache-flag-error](https://user-images.githubusercontent.com/13946/46364726-40111980-c63c-11e8-993b-6368ccc21f7a.png)

**To Replicate**
1. When running PHP 7.2 add a new flag in the CP. 
2. If that was your first flag, attempt to add a second flag.
3. You should see the red flash notice (screenshot attached)

**Environment Information:**

PHP version | 7.2.8
PostgreSQL 9.6.6
Imagick 3.4.3 (ImageMagick 6.7.8-9)
Craft Pro 3.0.25
Yii Version 2.0.15.1

**Comment by mmikkel** [comment]
Hi @bernsno – thanks for the detailed report! I'll take a look at that ASAP.

**Comment by mmikkel** [comment]
@bernsno Fixed in v. [1.0.3](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.0.3).
