### ISSUE TITLE
Cache break on future published entries?

### ISSUE THREAD

**Issue by ryanmasuga** [mmikkel/CacheFlag-Craft3#5]
Something a client noticed is that when they set an entry to go live at a future date, the index/listing page where that new entry should appear at the top (which is cached by Cache Flag) doesn’t update—they have to clear the cache for it to register. Is there something we can do to get Cache Flag to break a certain section's entries when a future published item goes live? Might we add a tag under `craft\elements\Entry` Element Types?

**Comment by mmikkel** [comment]
Craft doesn't dispatch any event or the like when an entry moves from `pending` to `published` status, so I'm not seeing any feasible way to have Cache Flag automatically clear caches for this use case.

The best workaround I can think of is to – before the `{% cacheflag %}` tag – query for _the first pending element_ (i.e. `status: 'pending'` and order the query by `postDate ASC`), and then use that element's timestamp for the `{% cacheflag %}` tag's `until` directive.

**Comment by ryanmasuga** [comment]
Interesting idea for a solution - thanks!
