### ISSUE TITLE
Save cache flag settings to project config

### ISSUE THREAD

**Issue by wbrowar** [mmikkel/CacheFlag-Craft3#6]
Hey Mats,

I haven't checked if this is in the upcoming changes yet, but what do you think about storing Cache Flag settings into project config and then turning off the ability to edit them based on `allowAdminChanges`?

Since my templates and project config get deployed together, it's most ideal to be able to configure Cache Flag in my `dev` environment and then push up that config along with my templates.

Thanks,
Will

**Comment by mmikkel** [comment]
Hi @wbrowar – thanks for contributing. TBH I hadn't really considered Project Config support for Cache Flag yet, but I'm on board with your suggestions. Marking this as an enhancement and unfortunately can't give you an ETA, but I'll get around to it :)

**Comment by mmikkel** [comment]
Cache Flag 1.2.0 (Craft 3.5.x only) adds support for Project Config.
