### ISSUE TITLE
Timeout in `deleteCaches` function

### ISSUE THREAD

**Issue by rungta** [mmikkel/CacheFlag-Craft3#7]
Consistently getting a timeout on this line when the cache size is crossing a certain threshold.
https://github.com/mmikkel/CacheFlag-Craft3/blob/b1065f17be6afc502310cd620e700b77b4ca4ee6/src/services/CacheFlagService.php#L403

```
yii\base\ErrorException: Maximum execution time of 30 seconds exceeded in
/srv/users/serverpilot/apps/ibsv2-c3/indiabioscience/vendor/mmikkel/cache-flag/src/services/CacheFlagService.php:403
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

I could increase the `max_execution_time` to more than 30 seconds, but it looks odd that this function is taking so much time. The actual cache deletion happens via a queued task (right?) which runs just fine, but the act of scheduling the cache deletion task seems to be taking longer than 30 seconds. Is this expected behaviour?

**Comment by mmikkel** [comment]
Hi @rungta,

Hm, I don't think this has anything to do with the actual cache deletion; it's probably the `foreach` loop on line 401 in [`CacheFlagService::deleteCaches`](https://github.com/mmikkel/CacheFlag-Craft3/blob/b1065f17be6afc502310cd620e700b77b4ca4ee6/src/services/CacheFlagService.php#L401).

I can refactor that method to be more performant, but just curious – do you have any idea how many caches it's trying to delete when it times out?

**Comment by rungta** [comment]
>Hm, I don't think this has anything to do with the actual cache deletion; it's probably the foreach loop on line 401 in CacheFlagService::deleteCaches.

Yup, that’s what I suspect too.

I forgot to check on the exact number before clearing all caches, but looking at a database dump around the time of the error, I see that the `craft_templatecaches` table has a count of 101759.

**Comment by mmikkel** [comment]
Thanks for the quick followup, @rungta – >100k rows is a respectable number of caches :D

I'll do some testing and see if I can optimise this ASAP.

**Comment by rungta** [comment]
> 100k rows is a respectable number of caches :D

Right 😱!? I was also a little surprised at that number. We don’t actually have that many pages on the site, but we do have a few sections with multiple sets of filters, and each filter combination results in a unique URL, which then gets cached. Hence the permutations add up fairly quickly, and it looks like someone is crawling the entire site and hitting all unique URLs, resulting in these many caches being generated.

> I'll do some testing and see if I can optimise this ASAP.

Thanks a bunch! Much appreciated.

**Comment by mmikkel** [comment]
Resolved in [Cache Flag v. 1.1.0](https://github.com/mmikkel/CacheFlag-Craft3/releases/tag/1.1.0).
