### ISSUE TITLE
Error Call to undefined method Stringy

### ISSUE THREAD

**Issue by mjatharvest** [mmikkel/CacheFlag-Craft3#8]
Hey there,

On Craft 3.3.0.1

I am getting an error within the Craft Control Panel when trying to view `/admin/cache-flag`

```
Call to undefined method Stringy\Stringy::snakeize()
```

**Comment by mmikkel** [comment]
Hi @mjatharvest, thanks for reporting.

I think Craft swapped out the [Stringy](https://github.com/danielstjules/Stringy) library for something else in Craft 3.3. 

I'll get a fix out shortly, in the meantime you could try to `composer require` the Stringy library yourself (i.e. `composer require danielstjules/stringy` from your project's root folder), as a hotfix.

**Comment by mmikkel** [comment]
Hi @mjatharvest – I'm not able to reproduce this issue, and CacheFlag doesn't appear to actually use the Stringy library. I suspect the problem is elsewhere...

Any chance you can turn on [`devMode`](https://docs.craftcms.com/v3/config/config-settings.html#devmode) and share a full stack trace?

**Comment by mjatharvest** [comment]
Thanks for the quick reply @mmikkel 

I'm on Craft 3.3.0.1
Using CacheFlag 1.0.3

A full stack trace is attached.

For me, the issue is related to the `|snake` twig filter on line 35 of `index.twig` at `vendor/mmikkel/cache-flag/src/templates/index.twig`

PDF of stack trace here:
[Error.pdf](https://github.com/mmikkel/CacheFlag-Craft3/files/3584160/Error.pdf)

**Comment by mjatharvest** [comment]
![Screen Shot 2019-09-06 at 8 32 03 AM](https://user-images.githubusercontent.com/285877/64432272-d2f2d900-d081-11e9-9939-89357b8004e0.png)

Let me know if there is anything other info that would be helpful for you to have.

**Comment by mmikkel** [comment]
Thanks a lot for the extra info, @mjatharvest!

I don't think this is a problem with CacheFlag – [`snake`](https://docs.craftcms.com/v3/dev/filters.html#snake) is actually a core filter, and the error occurs inside Craft's StringHelper class. I know [there's been some issues with Stringy on PHP 7.3](https://github.com/craftcms/cms/issues/4753), and Craft actually swapped out the Stringy package for a different distribution, in Craft 3.3.0.

You'll need to get in touch with support@craftcms.com (or file an issue to the [Craft repo](https://github.com/craftcms/cms/issues)).
